# Generated by Django 5.2.12 on 2026-03-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('lr', 'Linear Regression'), ('rf', 'Random Forest'), ('xgb', 'XGBoost')], max_length=50)),
                ('metrics', models.JSONField(default=dict)),
                ('feature_importance', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
            ],
            options={
                'ordering': ['-trained_at'],
                'unique_together': {('name', 'dataset')},
            },
        ),
    ]
